#!/bin/bash
set -e

mkdir -p rus
cd rus

wget http://biogeo.ucdavis.edu/data/gadm2/shp/RUS_adm.zip
unzip RUS_adm.zip

ogr2ogr -f GeoJSON subunits.json RUS_adm1.shp
topojson -e RUS_adm2.csv -s 1e-7 -p -o russia.json subunits.json --no-stitch-poles
rm subunits.json

