#!/bin/bash
set -e

mkdir -p rus
cd rus
wget http://gis-lab.info/data/rusbounds-rosreestr/regions2010_alb_shp.7z
7za e regions2010_wgs_shp.7z
wget http://biogeo.ucdavis.edu/data/gadm2/shp/UKR_adm.zip
unzip UKR_adm.zip

ogr2ogr -f GeoJSON subunits.json regions2010_wgs.shp
ogr2ogr -where "ID_1 IN ('4', 20)"  -f GeoJSON subunits_ua.json UKR_adm1.shp
iconv subunits.json -f cp1251 -t utf8 -o subunits1.json
mv subunits1.json subunits.json
sed s/"NAME_1"/"region"/g subunits_ua.json > subunits1_ua.json
mv subunits1_ua.json subunits_ua.json
topojson -s 1e-7 --no-stitch-poles -e ../region_names.tsv --id-property=region,region -p -o russia.json -- subunits.json subunits_ua.json 
rm subunits.json subunits_ua.json 

